version: '2'
services:
  # web with xdebug - actency images
  web:
    # actency/docker-apache-php available tags: latest, 7.0, 5.6, 5.5, 5.4, 5.3
    image: actency/docker-apache-php:5.6
    ports:
      - "80:80"
    environment:
      - SERVERNAME=poc-travis-behat.loc
      - SERVERALIAS=poc-travis-behat.loc
      - DOCUMENTROOT=htdocs
    volumes:
      - /home/docker/projets/poc-bdd/:/var/www/html/
      - /home/docker/.ssh/:/var/www/.ssh/
    links:
      - database:mysql
      - mailhog
    tty: true

  # database container - actency images
  database:
    # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
    image: actency/docker-mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbusr
      - MYSQL_PASSWORD=dbpwd
    #volumes:
      #- /my/custom:/etc/mysql/conf.d/

  # phpmyadmin container - actency images
  phpmyadmin:
    image: actency/docker-phpmyadmin
    ports:
      - "8010:80"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - UPLOAD_SIZE=1G
    links:
      - database:mysql

  # mailhog container - official images
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
